"""empty message

Revision ID: 0cf5d487d132
Revises: 1c295781695a
Create Date: 2023-02-08 17:01:39.576124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf5d487d132'
down_revision = '1c295781695a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('tlf', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_users',
    sa.Column('slack_id', sa.String(), nullable=False),
    sa.Column('current_username', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.CheckConstraint('priority <= 10', name='check_priority_range_max'),
    sa.CheckConstraint('priority >= 1', name='check_priority_range_min'),
    sa.PrimaryKeyConstraint('slack_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('finalized', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('cloudinary_id', sa.String(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['slack_users.slack_id'], ),
    sa.PrimaryKeyConstraint('cloudinary_id')
    )
    op.create_table('ratings',
    sa.Column('slack_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating <= 5', name='check_rating_range_max'),
    sa.CheckConstraint('rating >= 1', name='check_rating_range_min'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['slack_id'], ['slack_users.slack_id'], ),
    sa.PrimaryKeyConstraint('slack_id', 'restaurant_id')
    )
    op.create_table('invitations',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('slack_id', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rsvp', sa.Enum('attending', 'not attending', 'unanswered', name='rsvp'), server_default='unanswered', nullable=False),
    sa.Column('reminded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['slack_id'], ['slack_users.slack_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'slack_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    op.drop_table('ratings')
    op.drop_table('images')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('slack_users')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
