"""people_per_event_on_event_field

Revision ID: 2fc5d793c575
Revises: d47f2f92a586
Create Date: 2023-03-10 18:36:12.184671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc5d793c575'
down_revision = 'd47f2f92a586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('people_per_event', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'people_per_event')
    # ### end Alembic commands ###
