"""added channel_id

Revision ID: 735e0ed20026
Revises: 790e103a28ba
Create Date: 2023-03-04 19:12:27.882129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735e0ed20026'
down_revision = '790e103a28ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_organizations', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_organizations', 'channel_id')
    # ### end Alembic commands ###
