"""slack_org image and user

Revision ID: 790e103a28ba
Revises: 121a01854727
Create Date: 2023-03-03 17:28:17.631915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790e103a28ba'
down_revision = '121a01854727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('slack_organization_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'images', 'slack_organizations', ['slack_organization_id'], ['team_id'])
    op.add_column('users', sa.Column('slack_organization_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'slack_organizations', ['slack_organization_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'slack_organization_id')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'slack_organization_id')
    # ### end Alembic commands ###
