"""on group delete

Revision ID: 87db71f000d7
Revises: 517fd200010d
Create Date: 2023-03-11 22:09:19.982240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87db71f000d7'
down_revision = '517fd200010d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_group_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_group_id_fkey', 'events', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
