"""slack message on invitation

Revision ID: a78911713d44
Revises: 0cf5d487d132
Create Date: 2023-02-18 09:43:56.466100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78911713d44'
down_revision = '0cf5d487d132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_messages',
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ts', 'channel_id')
    )
    op.add_column('invitations', sa.Column('slack_message_channel', sa.String(), nullable=True))
    op.add_column('invitations', sa.Column('slack_message_ts', sa.String(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'slack_messages', ['slack_message_channel', 'slack_message_ts'], ['channel_id', 'ts'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'slack_message_ts')
    op.drop_column('invitations', 'slack_message_channel')
    op.drop_table('slack_messages')
    # ### end Alembic commands ###
