"""remove_nullable_slack_organization_id

Revision ID: d47f2f92a586
Revises: 349e8d92de29
Create Date: 2023-03-10 17:03:28.082644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47f2f92a586'
down_revision = '349e8d92de29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('images', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('slack_users', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slack_users', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('images', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'slack_organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
