"""Added priority field to user table

Revision ID: ff17a933d7cd
Revises: 
Create Date: 2022-08-21 16:40:56.411651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff17a933d7cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('priority', sa.Integer(), nullable=False, server_default="1"))
    op.create_check_constraint('check_priority_range_min', 'slack_users', sa.Column('priority') >= 1)
    op.create_check_constraint('check_priority_range_max', 'slack_users', sa.Column('priority') <= 10)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_users', 'priority')
    op.drop_constraint('check_priority_range_min', 'slack_users')
    op.drop_constraint('check_priority_range_max', 'slack_users')
    # ### end Alembic commands ###
