FROM python:3.9-alpine

WORKDIR /srv/bot

COPY bot/requirements.txt /tmp/
WORKDIR /tmp
RUN \
 apk add --no-cache build-base && \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 pip install -r requirements.txt && \
 apk --purge del .build-deps

WORKDIR /srv/bot

CMD python main.py
